# Generated by Django 3.2 on 2021-12-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app3model',
            old_name='body',
            new_name='body_field',
        ),
    ]
