# Generated by Django 3.2 on 2021-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_alter_app3model_body_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app3model',
            name='body_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
